export const SEARCH_USER_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USER_FAIL = 'SEARCH_USERS_FAIL'
export const SEARCH_USER_PENDING = 'SEARCH_USER_PENDING'
export const SET_RESULTS_PAGE='SET_RESULTS_PAGE';
export const SEARCH_REPO_PENDING='SEARCH_REPO_PENDING';
export const SEARCH_REPO_SUCCESS='SEARCH_REPO_SUCCESS';
export const SEARCH_REPO_FAIL='SEARCH_REPO_FAIL';